repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
      - id: pretty-format-json
        args: [--autofix]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.40.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.2.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.47.0
          - eslint-plugin-toml@0.5.0
        files: \.toml$ # Only lint toml files
        types: [file]
        args: ["--fix"]
  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
      - id: pip-audit
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: dockerfile_lint
  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/lk16/detect-missing-init
    rev: v0.1.6
    hooks:
      - id: detect-missing-init
        args: ["--python-folders", "pipelines"]
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.6
    hooks:
      - id: sqlfluff-fix
      - id: sqlfluff-lint
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        types_or: [python, markdown]
        additional_dependencies: [tomli]
  - repo: https://github.com/jendrikseipp/vulture
    rev: "v2.11"
    hooks:
      - id: vulture
        args: ["pipelines", "--min-confidence=80"]
  - repo: https://github.com/Casper321/reST-docstring-checker
    rev: v0.0.4
    hooks:
      - id: rest-docstring-checker
        args: ["--strict"]
  - repo: https://github.com/andrei-shabanski/poetry-plugin-sort
    rev: v0.2.1
    hooks:
      - id: poetry-sort
  # Ensure parity by running `pyright` locally.
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: bash -c 'pyright pipelines tests'
        language: system
        types: [python]
        require_serial: true
