# Pipeline specific overrides for production are defined here.

sample:
  key: sample_value_override_for_production

  price:
    multiplier: 10

data_connector_options:
  output_database:
    schema: sample
    if_exists: replace
