# List of available data connectors.
# In a pipeline you pick one or several of these,
# to use for data input and output.

default_database: &default_database
  type: database
  dialect: ${DB_DIALECT}
  host: ${DB_HOST}
  db_name: ${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASSWORD}

data_connector_options:
  input_files:
    type: file
    path: data/input/{pipeline}

  output_files:
    type: file
    path: data/output/{pipeline}

  input_fixtures:
    type: file
    path: data/fixtures/input/{pipeline}

  output_fixtures:
    type: file
    path: data/fixtures/output/{pipeline}

  input_gcs:
    type: gcs
    bucket_name: sample
    path: pipelines/input/{pipeline}

  output_gcs:
    type: gcs
    bucket_name: sample
    path: pipelines/output/{pipeline}

  input_database:
    <<: *default_database

  output_database:
    <<: *default_database
