# List of available data connectors.
# In a pipeline you pick one or several of these,
# to use for data input and output.

data_connector_options:
  input_files:
    type: file
    path: data/input/{pipeline}

  output_files:
    type: file
    path: data/output/{pipeline}

  input_fixtures:
    type: file
    path: data/fixtures/input/{pipeline}

  output_fixtures:
    type: file
    path: data/fixtures/output/{pipeline}

  input_gcs:
    type: gcs
    bucket_name: sample
    path: pipelines/input/{pipeline}

  output_gcs:
    type: gcs
    bucket_name: sample
    path: pipelines/output/{pipeline}
