# Configuration related to logging.

version: 1
disable_existing_loggers: true

formatters:
  default:
    format: "[%(asctime)s][%(levelname)s][%(processName)s][%(name)s:%(lineno)d] %(message)s"
  colored:
    (): coloredlogs.ColoredFormatter
    format: "[%(asctime)s][%(levelname)s][%(processName)s][%(name)s:%(lineno)d] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: colored
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: logs/output.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

root:
  level: INFO
  handlers: [console, file_handler]
