name: CD - Push Docker Image

# This workflow is triggered after the CI pipeline completes.
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - CI
    branches:
      - main
    types:
      - completed

env:
  IMAGE_NAME: pipelines

jobs:
  build-and-push:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment: ${{ (github.ref_name == 'main' && 'production') || github.ref_name }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Image
        run: make build_base

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ vars.REGISTRY }} --quiet

      - name: Push Image
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ vars.REGISTRY }}/${{ vars.GCP_PROJECT_ID }}/${{ vars.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ vars.REGISTRY }}/${{ vars.GCP_PROJECT_ID }}/${{ vars.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
